name: Lighthouse

on: [pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.2
        id: waitFor200
        with:
          site_name: "sueldo"
          max_timeout: 120 # 2 Minutes
      - name: Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: ${{ steps.waitFor200.outputs.url }}
          runs: 5
          uploadArtifacts: true
          budgetPath: ./budget.json
